/**
 * ============================================================
 *  Destiny 2 本赛季武器清单 — 数据填写文件
 * ============================================================
 *  推荐用 editor.html 可视化编辑后「导出 data.js」覆盖本文件。
 *  每把武器可分别填写 PVE / PVP 评级与 Perk 组合。
 * ============================================================
 */

const WEAPON_DATA = {
  "seasonTitle": "凯旋纪念碑 全武器刷取清单",
  "seasonNote": "",
  "sections": [
    {
      "id": "seasonal",
      "title": "扭曲目的地",
      "weapons": [
        {
          "name": "塔霍马01",
          "weaponType": "融合步枪",
          "ammoType": "特殊",
          "ratingPve": "C+",
          "ratingPvp": "",
          "frame": "攻击",
          "rpm": "",
          "element": "缚丝",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "丰盈满溢/嫉妒刺客/金中藏弹",
          "perk4Pve": "洪涝/聚合充能/受控连射",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "迪凯特02",
          "weaponType": "自动步枪",
          "ammoType": "主要",
          "ratingPve": "A+",
          "ratingPvp": "",
          "frame": "支援",
          "rpm": "600",
          "element": "冰影",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "医治/羸弱能量球",
          "perk4Pve": "互惠",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "艾恩伍德03",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "B+",
          "ratingPvp": "",
          "frame": "散射",
          "rpm": "100",
          "element": "虚空",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "冲击支撑/威胁移除器/拳击手",
          "perk4Pve": "失衡弹药/腹背受敌/雪上加霜",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "戴德霍斯04",
          "weaponType": "微型冲锋枪",
          "ammoType": "主要",
          "ratingPve": "B",
          "ratingPvp": "B+",
          "frame": "适配",
          "rpm": "900",
          "element": "冰影",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "霜华窃取者/即兴弹药",
          "perk4Pve": "结晶残花/拳击手/集体拳击",
          "perk1Pvp": "锻造膛线",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "测距仪",
          "perk4Pvp": "目标锁定",
          "note": ""
        },
        {
          "name": "艾伦05",
          "weaponType": "狙击步枪",
          "ammoType": "特殊",
          "ratingPve": "C+",
          "ratingPvp": "C+",
          "frame": "适配",
          "rpm": "90",
          "element": "缚丝",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "事不过四",
          "perk4Pve": "火线/精准工具/超级杀戮弹匣",
          "perk1Pvp": "槽化枪管",
          "perk2Pvp": "稳固弹药",
          "perk3Pvp": "孤狼",
          "perk4Pvp": "移动目标",
          "note": ""
        },
        {
          "name": "迪亚布勒雷06",
          "weaponType": "机枪",
          "ammoType": "威能",
          "ratingPve": "C+",
          "ratingPvp": "",
          "frame": "速射",
          "rpm": "900",
          "element": "缚丝",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "幼雏/喂食狂热",
          "perk4Pve": "巨脉蜻蜓/击杀记录",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ],
      "note": "在每小时轮换的扭曲目的地，完成公共事件或开启异常信号奖励箱获取"
    },
    {
      "id": "世界掉落-mtpqchmi",
      "title": "世界掉落",
      "note": "目的地宝箱/遗失区域宝箱/高塔枪匠霍桑记忆水晶",
      "weapons": [
        {
          "name": "钢羽中继器",
          "weaponType": "自动步枪",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "速射",
          "rpm": "720",
          "element": "动能",
          "antiChamp": "过载",
          "showPvePerk": false,
          "showPvpPerk": false,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": "perk池全是垃圾"
        },
        {
          "name": "完美悖论",
          "weaponType": "霰弹枪",
          "ammoType": "特殊",
          "ratingPve": "S",
          "ratingPvp": "",
          "frame": "速射",
          "rpm": "140",
          "element": "动能",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "阻止力/拳击手/威胁移除器",
          "perk4Pve": "战壕炮管/全明星/雪上加霜",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "繁文缛节",
          "weaponType": "斥候步枪",
          "ammoType": "主要",
          "ratingPve": "C+",
          "ratingPvp": "",
          "frame": "轻质",
          "rpm": "200",
          "element": "冰影",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "霜华窃取者/羸弱能量球/爆破专家",
          "perk4Pve": "墓碑/高爆载荷",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": "听说羸弱能量球+高爆载荷的产球速度还可以"
        },
        {
          "name": "礼拜",
          "weaponType": "榴弹发射器",
          "ammoType": "特殊",
          "ratingPve": "B+",
          "ratingPvp": "",
          "frame": "双重火力",
          "rpm": "",
          "element": "冰影",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "嫉妒军械库",
          "perk4Pve": "冰冷弹匣/金中藏弹",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "夜神长存V",
          "weaponType": "融合步枪",
          "ammoType": "特殊",
          "ratingPve": "A",
          "ratingPvp": "B+",
          "frame": "高冲击力",
          "rpm": "",
          "element": "缚丝",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "嫉妒刺客/金中藏弹",
          "perk4Pve": "受控连射",
          "perk1Pvp": "螺旋膛线/锻造膛线",
          "perk2Pvp": "弹头保险丝",
          "perk3Pvp": "越战越勇",
          "perk4Pvp": "快速启动",
          "note": ""
        },
        {
          "name": "炫彩突袭",
          "weaponType": "自动步枪",
          "ammoType": "主要",
          "ratingPve": "C+",
          "ratingPvp": "A+",
          "frame": "速射",
          "rpm": "720",
          "element": "动能",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "阻止力",
          "perk4Pve": "动能震颤",
          "perk1Pvp": "加长枪管/全口径枪膛/锻造膛线",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "动态减摆/痛苦之道",
          "perk4Pvp": "狂暴/动能震颤/杀戮弹匣",
          "note": ""
        },
        {
          "name": "无尽之路8",
          "weaponType": "脉冲步枪",
          "ammoType": "主要",
          "ratingPve": "C",
          "ratingPvp": "A",
          "frame": "轻质",
          "rpm": "450",
          "element": "电弧",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "蜻蜓/涓流充能/爆破专家",
          "perk4Pve": "风暴涌动/伏特子弹",
          "perk1Pvp": "全口径枪膛",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "移动目标",
          "perk4Pvp": "杀戮弹匣",
          "note": ""
        },
        {
          "name": "诱惑之钩",
          "weaponType": "刀剑",
          "ammoType": "威能",
          "ratingPve": "B",
          "ratingPvp": "",
          "frame": "铸造者",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "羸弱能量球",
          "perk4Pve": "震颤反馈/风暴涌动/居合连斩",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "日心QSC",
          "weaponType": "手枪",
          "ammoType": "主要",
          "ratingPve": "A",
          "ratingPvp": "A",
          "frame": "轻质",
          "rpm": "360",
          "element": "烈日",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "治疗弹匣",
          "perk4Pve": "辉耀炽热",
          "perk1Pvp": "加长枪管/全口径枪膛/锻造膛线",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "治疗弹匣/永动不歇/测距仪/移动目标",
          "perk4Pvp": "杀戮弹匣/精准工具",
          "note": ""
        },
        {
          "name": "棘蛇",
          "weaponType": "微型冲锋枪",
          "ammoType": "主要",
          "ratingPve": "B",
          "ratingPvp": "C+",
          "frame": "轻质",
          "rpm": "900",
          "element": "烈日",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "喂食狂热/治疗弹匣",
          "perk4Pve": "蜻蜓/燃烧野心",
          "perk1Pvp": "锻造膛线/小口径枪膛",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "治疗弹匣/禅意时刻/动态减摆",
          "perk4Pvp": "测距仪/移动目标",
          "note": ""
        },
        {
          "name": "黄铜攻击",
          "weaponType": "手枪",
          "ammoType": "主要",
          "ratingPve": "A+",
          "ratingPvp": "B",
          "frame": "重型点射",
          "rpm": "325",
          "element": "虚空",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "冲击支撑",
          "perk4Pve": "失衡弹药/狂乱",
          "perk1Pvp": "加长枪管/锻造膛线",
          "perk2Pvp": "大口径弹药/弹跳型弹药",
          "perk3Pvp": "滑行健射/快速命中1",
          "perk4Pvp": "失衡弹药/狂暴",
          "note": ""
        },
        {
          "name": "格网队长",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "潮人",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "入境监控",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "单人行动-mtptp6m5",
      "title": "单人行动",
      "note": "",
      "weapons": [
        {
          "name": "指挥链",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "叛乱疾呼",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "公平审判",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "最后仪式",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "溪谷-X",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "绝对音高",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "骑士之火",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "权势",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "鲁莽致险",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "黄道卷线杆",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "恶咒",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "高亢",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "火力战队行动-mtptrzbf",
      "title": "火力战队行动",
      "note": "",
      "weapons": [
        {
          "name": "召集反曲弓",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "下班时刻",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "加时交锋",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "暗夜魅影",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "无名午夜",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "注视焦点",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "忠侍左轮",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "主原料",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "光明前景",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "极光破晓",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "竞技场行动-mtptud7f",
      "title": "竞技场行动",
      "note": "",
      "weapons": [
        {
          "name": "嗡鸣铁锭",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "恶意尖牙",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "多多罗的凝视",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "绽放兰花",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "史赛克的老练",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "锤头",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "高炉",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "无感",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "轰鸣巨人",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "回火发电机",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "巅峰行动-mtptwhq6",
      "title": "巅峰行动",
      "note": "",
      "weapons": [
        {
          "name": "驱逐引擎",
          "weaponType": "榴弹发射器",
          "ammoType": "特殊",
          "ratingPve": "S",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "冰影",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "叫啥来着",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "拯救者的喝彩",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "零镇静",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "崇拜",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "完美逆行",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "回文",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "食莲者",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "急锋",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "死从天降",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "热血上头",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "熔炉竞技场行动-mtptyql4",
      "title": "熔炉竞技场行动",
      "note": "",
      "weapons": [
        {
          "name": "舵手",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "乔科斯的长剑",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "魔鬼中的天使",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "无尽风暴",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "兰迪飞刃",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "秋风",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "越界",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "忧伤韵文",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "幸存者碑文",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "恸哭",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "冰冻轨道",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "束缚化身IV",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "奥斯里斯试炼-mtpu1ya6",
      "title": "奥斯里斯试炼",
      "note": "",
      "weapons": [
        {
          "name": "信使",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "任性原罪",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "召唤灵师",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "渊博学者",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "孤空伤痕",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "艾莎之眷",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "崇高真理",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "锐利之蓟",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "审判官",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "烈焰之锤",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "沙玉拉之怒",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "炎阳灵眼",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "放逐诅咒",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "明日回答",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "铁旗-mtpu5ju2",
      "title": "铁旗",
      "note": "",
      "weapons": [
        {
          "name": "邪冬的谎言",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "前进之道",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "陈旧的尖顶",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "睿智责难",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "克瑞米尔之匕",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "冈诺拉之斧",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "雷古斯克之誓",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "多机系统CCX",
          "weaponType": "微型冲锋枪",
          "ammoType": "主要",
          "ratingPve": "S",
          "ratingPvp": "A+",
          "frame": "轻质",
          "rpm": "900",
          "element": "动能",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "羸弱能量球",
          "perk4Pve": "动能震颤",
          "perk1Pvp": "全口径枪膛/锻造膛线/小口径枪膛",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "移动目标/测距仪/动态减摆/阻止力",
          "perk4Pvp": "目标锁定/动能震颤/杀戮弹匣/武器大师",
          "note": "PVP用途中，阻止力需与目标锁定/动能震颤搭配使用"
        },
        {
          "name": "有限冲击器",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "A",
          "frame": "",
          "rpm": "",
          "element": "烈日",
          "antiChamp": "",
          "showPvePerk": false,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "未竟之终",
          "weaponType": "狙击步枪",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "牡鹿之角",
          "weaponType": "战斗弓箭",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "熊啸",
          "weaponType": "火箭发射器",
          "ammoType": "威能",
          "ratingPve": "A",
          "ratingPvp": "",
          "frame": "高冲击力",
          "rpm": "15",
          "element": "烈日",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "爆破专家/自动填装枪套/重建/爆炸光能",
          "perk4Pve": "集束炸弹/收割者贡品",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "增压精准",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "致命丰裕",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "智谋行动-mtpup1n6",
      "title": "智谋行动",
      "note": "",
      "weapons": [
        {
          "name": "痛苦的饥饿",
          "weaponType": "自动步枪",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "噤声",
          "weaponType": "战斗弓箭",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "21%的亢奋",
          "weaponType": "机枪",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "恶兆",
          "weaponType": "火箭发射器",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "信任",
          "weaponType": "手炮",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "唯一幸存者",
          "weaponType": "狙击步枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "备用口粮",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "冰影",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "末日",
          "weaponType": "榴弹发射器",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "最后生存者",
          "weaponType": "霰弹枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "烈日",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "紧急求生包",
          "weaponType": "微型冲锋枪",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "故人往事",
          "weaponType": "脉冲步枪",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "动能",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "巨蟒",
          "weaponType": "霰弹枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "虚空",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "猛攻-mtpush9l",
      "title": "猛攻",
      "note": "",
      "weapons": [
        {
          "name": "隐士",
          "weaponType": "微型冲锋枪",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "S",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "冲击支撑",
          "perk4Pve": "失衡弹药/混沌重塑",
          "perk1Pvp": "锻造膛线/小口径枪膛",
          "perk2Pvp": "弹跳型弹药",
          "perk3Pvp": "动态减摆",
          "perk4Pvp": "武器大师",
          "note": ""
        },
        {
          "name": "绞刑判官SR4",
          "weaponType": "斥候步枪",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "继承",
          "weaponType": "狙击步枪",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "山巅",
          "weaponType": "榴弹发射器",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "陨落铡刀",
          "weaponType": "刀剑",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "自制",
          "weaponType": "榴弹发射器",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "月之狂嚎",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "边缘交通",
          "weaponType": "榴弹发射器",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "艾尔西的步枪",
          "weaponType": "脉冲步枪",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "午夜政变",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "赛雀联赛-mtpw7alp",
      "title": "赛雀联赛",
      "note": "",
      "weapons": [
        {
          "name": "维卡拉微冲4",
          "weaponType": "微型冲锋枪",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "韦兰迪夫-D",
          "weaponType": "脉冲步枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "核心星辰IV",
          "weaponType": "火箭发射器",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "狙猎MK.47",
          "weaponType": "自动步枪",
          "ammoType": "主要",
          "ratingPve": "S",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "渐速音-42",
          "weaponType": "融合步枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "三色矛头蝮-4BL",
          "weaponType": "",
          "ammoType": "",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "多人竞技-mtpyjcxe",
      "title": "多人竞技",
      "note": "",
      "weapons": []
    },
    {
      "id": "忠诚信条-溯回-mtpwn6fw",
      "title": "忠诚信条-溯回",
      "note": "高塔",
      "weapons": [
        {
          "name": "巴西游走蛛",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "龙䲢",
          "weaponType": "霰弹枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "毒鲉",
          "weaponType": "刀剑",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "",
          "rpm": "",
          "element": "烈日",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "翎尾鲉",
          "weaponType": "追踪步枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "适配",
          "rpm": "",
          "element": "缚丝",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "沉没",
          "weaponType": "战斗弓箭",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "高冲击力",
          "rpm": "",
          "element": "冰影",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "浪漫之死",
          "weaponType": "榴弹发射器",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "波形",
          "rpm": "",
          "element": "虚空",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "折叠根源",
          "weaponType": "火箭发射器",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "攻击",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "忠诚信条-无序-mtpwyoa1",
      "title": "忠诚信条-无序",
      "note": "",
      "weapons": [
        {
          "name": "奥菲欧王",
          "weaponType": "战斗弓箭",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "精密",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "苍鹭",
          "weaponType": "偃月",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "攻击",
          "rpm": "",
          "element": "虚空",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "行动项目",
          "weaponType": "追踪步枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "适配",
          "rpm": "",
          "element": "冰影",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "微死亡",
          "weaponType": "火箭发射器",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "精密",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "机巧纬线",
          "weaponType": "榴弹发射器",
          "ammoType": "特殊",
          "ratingPve": "S",
          "ratingPvp": "",
          "frame": "微型导弹",
          "rpm": "",
          "element": "缚丝",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "第六感",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "攻击",
          "rpm": "120",
          "element": "缚丝",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "强硬切割",
          "weaponType": "刀剑",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "适配",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "忠诚信条-至日-mtpy8nx2",
      "title": "忠诚信条-至日",
      "note": "",
      "weapons": [
        {
          "name": "玫瑰罗盘",
          "weaponType": "霰弹枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "精密",
          "rpm": "",
          "element": "烈日",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "加冕对白",
          "weaponType": "火箭发射器",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "精密",
          "rpm": "",
          "element": "缚丝",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "幸运星",
          "weaponType": "战斗弓箭",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "轻质",
          "rpm": "",
          "element": "虚空",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "庆典飞行",
          "weaponType": "榴弹发射器",
          "ammoType": "特殊",
          "ratingPve": "S",
          "ratingPvp": "",
          "frame": "区域拒止",
          "rpm": "",
          "element": "缚丝",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "岁时之巅",
          "weaponType": "微型冲锋枪",
          "ammoType": "主要",
          "ratingPve": "S",
          "ratingPvp": "",
          "frame": "轻质",
          "rpm": "",
          "element": "烈日",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "远方黎明",
          "weaponType": "机枪",
          "ammoType": "威能",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "攻击",
          "rpm": "",
          "element": "烈日",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "快速增长",
          "weaponType": "狙击步枪",
          "ammoType": "特殊",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "速射",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "新玩意",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "攻击",
          "rpm": "120",
          "element": "冰影",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ]
    },
    {
      "id": "忠诚信条-奇异-mtpyd1ej",
      "title": "忠诚信条-奇异",
      "note": "",
      "weapons": []
    },
    {
      "id": "忠诚信条-曙光节-mtpydhng",
      "title": "忠诚信条-曙光节",
      "note": "",
      "weapons": []
    },
    {
      "id": "忠诚信条-守护者游戏-mtpydr8q",
      "title": "忠诚信条-守护者游戏",
      "note": "",
      "weapons": []
    },
    {
      "id": "忠诚信条-火力战队行动-mtpye41s",
      "title": "忠诚信条-火力战队行动",
      "note": "",
      "weapons": []
    },
    {
      "id": "忠诚信条-巅峰行动-mtpyeg7g",
      "title": "忠诚信条-巅峰行动",
      "note": "",
      "weapons": []
    },
    {
      "id": "忠诚信条-熔炉竞技场行动-mtpyeu0r",
      "title": "忠诚信条-熔炉竞技场行动",
      "note": "",
      "weapons": []
    },
    {
      "id": "忠诚信条-赛季武器-mtpyf6y6",
      "title": "忠诚信条-赛季武器",
      "note": "",
      "weapons": []
    },
    {
      "id": "萨瓦拉-mtpyfrea",
      "title": "高塔-指挥官萨瓦拉",
      "note": "",
      "weapons": []
    },
    {
      "id": "高塔-班西-44-mtpygvv1",
      "title": "高塔-班西-44",
      "note": "",
      "weapons": []
    },
    {
      "id": "高塔-领主沙克斯-mtpyhxvq",
      "title": "高塔-领主沙克斯",
      "note": "",
      "weapons": []
    },
    {
      "id": "高塔-军政官萨拉丁-mtpyj08p",
      "title": "高塔-军政官萨拉丁",
      "note": "",
      "weapons": []
    },
    {
      "id": "高塔-浪客-mtpylc1d",
      "title": "高塔-浪客",
      "note": "",
      "weapons": []
    },
    {
      "id": "高塔-圣人14号-mtpymoca",
      "title": "高塔-圣人14号",
      "note": "",
      "weapons": []
    },
    {
      "id": "发射基地-mtpypxjd",
      "title": "发射基地",
      "note": "",
      "weapons": []
    },
    {
      "id": "欧洲无人区-mtpyqels",
      "title": "欧洲无人区",
      "note": "",
      "weapons": []
    },
    {
      "id": "月球-mtpyw00t",
      "title": "月球",
      "note": "",
      "weapons": []
    },
    {
      "id": "月球-忧愁祭坛-mtpyqzcd",
      "title": "月球-忧愁祭坛",
      "note": "通过完成月球上的忧愁祭坛活动获得",
      "weapons": []
    },
    {
      "id": "涅索斯-mtpyu0ir",
      "title": "涅索斯",
      "note": "只能通过公共事件掉落",
      "weapons": []
    },
    {
      "id": "木卫二-mtpywsue",
      "title": "木卫二",
      "note": "",
      "weapons": []
    },
    {
      "id": "幽梦之城-mtpyx6lj",
      "title": "幽梦之城",
      "note": "",
      "weapons": []
    },
    {
      "id": "王座世界-mtpz0d3g",
      "title": "王座世界",
      "note": "",
      "weapons": []
    },
    {
      "id": "海王星-mtpyzb6e",
      "title": "海王星",
      "note": "",
      "weapons": []
    },
    {
      "id": "海王星-终端过载-mtpz4ipx",
      "title": "海王星-终端过载",
      "note": "",
      "weapons": []
    },
    {
      "id": "苍白之心-mtpz0p65",
      "title": "苍白之心",
      "note": "",
      "weapons": []
    },
    {
      "id": "开普勒-mtpzcsvp",
      "title": "开普勒",
      "note": "",
      "weapons": []
    },
    {
      "id": "无序边界-mtpzdjq0",
      "title": "无序边界",
      "note": "",
      "weapons": []
    },
    {
      "id": "永恒挑战-mtpzdpog",
      "title": "永恒挑战",
      "note": "",
      "weapons": []
    },
    {
      "id": "凯尔之陨-mtpzf2gu",
      "title": "异域任务-凯尔之陨",
      "note": "",
      "weapons": []
    },
    {
      "id": "异域任务-安可-mtpzfnuo",
      "title": "异域任务-安可",
      "note": "",
      "weapons": []
    },
    {
      "id": "异域任务-苦命鸳鸯-mtpzfxa0",
      "title": "异域任务-苦命鸳鸯",
      "note": "",
      "weapons": []
    },
    {
      "id": "异域任务-节点超控阿瓦隆-mtpzh943",
      "title": "异域任务-//节点.超控.阿瓦隆//",
      "note": "",
      "weapons": []
    },
    {
      "id": "异域任务-行动炽天使之盾-mtpzhjn7",
      "title": "异域任务-行动：炽天使之盾",
      "note": "",
      "weapons": []
    },
    {
      "id": "异域任务-暗屋之声-mtpzi3fa",
      "title": "异域任务-暗屋之声",
      "note": "",
      "weapons": []
    },
    {
      "id": "异域任务-前兆-mtpzid8o",
      "title": "异域任务-前兆",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-最后一愿-mtpznooz",
      "title": "突袭-最后一愿",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-救赎花园-mtpzoigu",
      "title": "突袭-救赎花园",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-深岩墓室-mtpzp0uq",
      "title": "突袭-深岩墓室",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-玻璃拱顶-mtpzm8hm",
      "title": "突袭-玻璃拱顶",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-门徒誓约-mtpzpa4g",
      "title": "突袭-门徒誓约",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-国王的陨落-mtpzn48h",
      "title": "突袭-国王的陨落",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-梦魇根源-mtpzpuba",
      "title": "突袭-梦魇根源",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-克洛塔的末日-mtpzmslc",
      "title": "突袭-克洛塔的末日",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-救赎边缘-mtpzq9pr",
      "title": "突袭-救赎的边缘",
      "note": "",
      "weapons": []
    },
    {
      "id": "突袭-永恒沙漠-mtpzqmpq",
      "title": "突袭-永恒沙漠",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-破碎王座-mtpzty0i",
      "title": "地牢-破碎王座",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-异端深渊-mtpzu4y7",
      "title": "地牢-异端深渊",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-预言-mtpzuc5y",
      "title": "地牢-预言",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-贪婪之握-mtpzuido",
      "title": "地牢-贪婪之握",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-二象性-mtpzuon3",
      "title": "地牢-二象性",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-守望者尖塔-mtpzuteb",
      "title": "地牢-守望者尖塔",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-深渊机灵-mtpzwmge",
      "title": "地牢-深渊机灵",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-战争领主的废墟-mtpzwvrm",
      "title": "地牢-战争领主的废墟",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-晚星之主-mtpzx2cj",
      "title": "地牢-晚星之主",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-分离教义-mtpzx847",
      "title": "地牢-分离教义",
      "note": "",
      "weapons": []
    },
    {
      "id": "地牢-平衡-mtpzxcql",
      "title": "地牢-平衡",
      "note": "",
      "weapons": []
    },
    {
      "id": "众神殿-mtpzxij8",
      "title": "众神殿",
      "note": "",
      "weapons": []
    }
  ],
  "updatedAt": "2026-09-06T15:58:38.789Z"
};
