/**
 * ============================================================
 *  Destiny 2 本赛季武器清单 — 数据填写文件
 * ============================================================
 *  推荐用 editor.html 可视化编辑后「导出 data.js」覆盖本文件。
 *  每把武器可分别填写 PVE / PVP 评级与 Perk 组合。
 * ============================================================
 */

const WEAPON_DATA = {
  "seasonTitle": "凯旋纪念碑 全武器刷取清单",
  "seasonNote": "",
  "sections": [
    {
      "id": "seasonal",
      "title": "扭曲目的地",
      "weapons": [
        {
          "name": "塔霍马01",
          "weaponType": "融合步枪",
          "ammoType": "特殊",
          "ratingPve": "C+",
          "ratingPvp": "",
          "frame": "攻击",
          "rpm": "",
          "element": "缚丝",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "丰盈满溢/嫉妒刺客/金中藏弹",
          "perk4Pve": "洪涝/聚合充能/受控连射",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "迪凯特02",
          "weaponType": "自动步枪",
          "ammoType": "主要",
          "ratingPve": "A+",
          "ratingPvp": "",
          "frame": "支援",
          "rpm": "600",
          "element": "冰影",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "医治/羸弱能量球",
          "perk4Pve": "互惠",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "艾恩伍德03",
          "weaponType": "手炮",
          "ammoType": "主要",
          "ratingPve": "B+",
          "ratingPvp": "",
          "frame": "散射",
          "rpm": "100",
          "element": "虚空",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "冲击支撑/威胁移除器/拳击手",
          "perk4Pve": "失衡弹药/腹背受敌/雪上加霜",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "戴德霍斯04",
          "weaponType": "微型冲锋枪",
          "ammoType": "主要",
          "ratingPve": "B",
          "ratingPvp": "B+",
          "frame": "适配",
          "rpm": "900",
          "element": "冰影",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "霜华窃取者/即兴弹药",
          "perk4Pve": "结晶残花/拳击手/集体拳击",
          "perk1Pvp": "锻造膛线",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "测距仪",
          "perk4Pvp": "目标锁定",
          "note": ""
        },
        {
          "name": "艾伦05",
          "weaponType": "狙击步枪",
          "ammoType": "特殊",
          "ratingPve": "C+",
          "ratingPvp": "C+",
          "frame": "适配",
          "rpm": "90",
          "element": "缚丝",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "事不过四",
          "perk4Pve": "火线/精准工具/超级杀戮弹匣",
          "perk1Pvp": "槽化枪管",
          "perk2Pvp": "稳固弹药",
          "perk3Pvp": "孤狼",
          "perk4Pvp": "移动目标",
          "note": ""
        },
        {
          "name": "迪亚布勒雷06",
          "weaponType": "机枪",
          "ammoType": "威能",
          "ratingPve": "C+",
          "ratingPvp": "",
          "frame": "速射",
          "rpm": "900",
          "element": "缚丝",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "幼雏/喂食狂热",
          "perk4Pve": "巨脉蜻蜓/击杀记录",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        }
      ],
      "note": "在每小时轮换的扭曲目的地，完成公共事件或开启异常信号奖励箱获取"
    },
    {
      "id": "世界掉落-mtpqchmi",
      "title": "世界掉落",
      "note": "目的地宝箱/遗失区域宝箱/高塔枪匠霍桑记忆水晶",
      "weapons": [
        {
          "name": "钢羽中继器",
          "weaponType": "自动步枪",
          "ammoType": "主要",
          "ratingPve": "",
          "ratingPvp": "",
          "frame": "速射",
          "rpm": "720",
          "element": "动能",
          "antiChamp": "过载",
          "showPvePerk": false,
          "showPvpPerk": false,
          "perk3Pve": "",
          "perk4Pve": "",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": "perk池全是垃圾"
        },
        {
          "name": "完美悖论",
          "weaponType": "霰弹枪",
          "ammoType": "特殊",
          "ratingPve": "S",
          "ratingPvp": "",
          "frame": "速射",
          "rpm": "140",
          "element": "动能",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "阻止力/拳击手/威胁移除器",
          "perk4Pve": "战壕炮管/全明星/雪上加霜",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "繁文缛节",
          "weaponType": "斥候步枪",
          "ammoType": "主要",
          "ratingPve": "C+",
          "ratingPvp": "",
          "frame": "轻质",
          "rpm": "200",
          "element": "冰影",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "霜华窃取者/羸弱能量球/爆破专家",
          "perk4Pve": "墓碑/高爆载荷",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": "听说羸弱能量球+高爆载荷的产球速度还可以"
        },
        {
          "name": "礼拜",
          "weaponType": "榴弹发射器",
          "ammoType": "特殊",
          "ratingPve": "B+",
          "ratingPvp": "",
          "frame": "双重火力",
          "rpm": "",
          "element": "冰影",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "嫉妒军械库",
          "perk4Pve": "冰冷弹匣/金中藏弹",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "夜神长存V",
          "weaponType": "融合步枪",
          "ammoType": "特殊",
          "ratingPve": "A",
          "ratingPvp": "B+",
          "frame": "高冲击力",
          "rpm": "",
          "element": "缚丝",
          "antiChamp": "势不可挡",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "嫉妒刺客/金中藏弹",
          "perk4Pve": "受控连射",
          "perk1Pvp": "螺旋膛线/锻造膛线",
          "perk2Pvp": "弹头保险丝",
          "perk3Pvp": "越战越勇",
          "perk4Pvp": "快速启动",
          "note": ""
        },
        {
          "name": "炫彩突袭",
          "weaponType": "自动步枪",
          "ammoType": "主要",
          "ratingPve": "C+",
          "ratingPvp": "A+",
          "frame": "速射",
          "rpm": "720",
          "element": "动能",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "阻止力",
          "perk4Pve": "动能震颤",
          "perk1Pvp": "加长枪管/全口径枪膛/锻造膛线",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "动态减摆/痛苦之道",
          "perk4Pvp": "狂暴/动能震颤/杀戮弹匣",
          "note": ""
        },
        {
          "name": "无尽之路8",
          "weaponType": "脉冲步枪",
          "ammoType": "主要",
          "ratingPve": "C",
          "ratingPvp": "A",
          "frame": "轻质",
          "rpm": "450",
          "element": "电弧",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "蜻蜓/涓流充能/爆破专家",
          "perk4Pve": "风暴涌动/伏特子弹",
          "perk1Pvp": "全口径枪膛",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "移动目标",
          "perk4Pvp": "杀戮弹匣",
          "note": ""
        },
        {
          "name": "诱惑之钩",
          "weaponType": "刀剑",
          "ammoType": "威能",
          "ratingPve": "B",
          "ratingPvp": "",
          "frame": "铸造者",
          "rpm": "",
          "element": "电弧",
          "antiChamp": "屏障",
          "showPvePerk": true,
          "showPvpPerk": false,
          "perk3Pve": "羸弱能量球",
          "perk4Pve": "震颤反馈/风暴涌动/居合连斩",
          "perk1Pvp": "",
          "perk2Pvp": "",
          "perk3Pvp": "",
          "perk4Pvp": "",
          "note": ""
        },
        {
          "name": "日心QSC",
          "weaponType": "手枪",
          "ammoType": "主要",
          "ratingPve": "A",
          "ratingPvp": "A",
          "frame": "轻质",
          "rpm": "360",
          "element": "烈日",
          "antiChamp": "过载",
          "showPvePerk": true,
          "showPvpPerk": true,
          "perk3Pve": "治疗弹匣",
          "perk4Pve": "辉耀炽热",
          "perk1Pvp": "加长枪管/全口径枪膛/锻造膛线",
          "perk2Pvp": "精确弹药",
          "perk3Pvp": "治疗弹匣/永动不歇/测距仪/移动目标",
          "perk4Pvp": "杀戮弹匣/精准工具",
          "note": ""
        }
      ]
    }
  ]
};
